#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA2C794A986419D8A (tstellar@redhat.com)
#
%define keepstatic 1
Name     : llvm13
Version  : 13.0.0
Release  : 2
URL      : https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/llvm-project-13.0.0.src.tar.xz
Source0  : https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/llvm-project-13.0.0.src.tar.xz
Source1  : https://github.com/KhronosGroup/SPIRV-Headers/archive/92f21c9b214178ce67cf1e31a00a33312590403a.tar.gz
Source2  : https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/refs/tags/v13.0.0.tar.gz
Source3  : https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.0/llvm-project-13.0.0.src.tar.xz.sig
Summary  : Google microbenchmark framework
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause ISC MIT MPL-2.0 NCSA
Requires: llvm13-bin = %{version}-%{release}
Requires: llvm13-lib = %{version}-%{release}
Requires: llvm13-license = %{version}-%{release}
Requires: llvm13-python = %{version}-%{release}
Requires: llvm13-python3 = %{version}-%{release}
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev Vulkan-Loader-dev Vulkan-Tools
BuildRequires : Z3-dev
BuildRequires : Z3-dev32
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : cmake
BuildRequires : doxygen
BuildRequires : elfutils-dev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : googletest-dev
BuildRequires : grep
BuildRequires : libffi-dev
BuildRequires : libffi-dev32
BuildRequires : libstdc++-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-dev32
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : lua-dev
BuildRequires : ncurses-dev
BuildRequires : ninja
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(32libffi)
BuildRequires : pkgconfig(libedit)
BuildRequires : pkgconfig(libffi)
BuildRequires : protobuf-dev
BuildRequires : pypi(absl_py)
BuildRequires : pypi(flit)
BuildRequires : pypi(graphviz)
BuildRequires : pypi(humanize)
BuildRequires : pypi(matplotlib)
BuildRequires : pypi(numpy)
BuildRequires : pypi(pandas)
BuildRequires : pypi(psutil)
BuildRequires : pypi(ptyprocess)
BuildRequires : pypi(pybind11)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(scipy)
BuildRequires : pypi(seaborn)
BuildRequires : python3-dev
BuildRequires : rsync
BuildRequires : sed
BuildRequires : swig
BuildRequires : valgrind-dev
BuildRequires : zlib-dev
BuildRequires : zlib-dev32
Patch1: llvm-0001-Improve-physical-core-count-detection.patch
Patch2: llvm-0002-Produce-a-normally-versioned-libLLVM.patch
Patch3: llvm-0003-Allow-one-more-FMA-fusion.patch
Patch4: clang-0001-Detect-Clear-Linux-and-apply-Clear-s-default-linker-.patch
Patch5: clang-0002-Make-Clang-default-to-Westmere-on-Clear-Linux.patch
Patch6: clang-0003-Add-the-LLVM-major-version-number-to-the-Gold-LTO-pl.patch
Patch7: clang-0004-Add-a-couple-more-f-instructions-that-GCC-has-that-C.patch

%description
Polly - Polyhedral optimizations for LLVM
-----------------------------------------
http://polly.llvm.org/

%package bin
Summary: bin components for the llvm13 package.
Group: Binaries
Requires: llvm13-license = %{version}-%{release}

%description bin
bin components for the llvm13 package.


%package dev
Summary: dev components for the llvm13 package.
Group: Development
Requires: llvm13-lib = %{version}-%{release}
Requires: llvm13-bin = %{version}-%{release}
Provides: llvm13-devel = %{version}-%{release}
Requires: llvm13 = %{version}-%{release}

%description dev
dev components for the llvm13 package.


%package dev32
Summary: dev32 components for the llvm13 package.
Group: Default
Requires: llvm13-lib32 = %{version}-%{release}
Requires: llvm13-bin = %{version}-%{release}
Requires: llvm13-dev = %{version}-%{release}

%description dev32
dev32 components for the llvm13 package.


%package extras-libclang
Summary: extras-libclang components for the llvm13 package.
Group: Default

%description extras-libclang
extras-libclang components for the llvm13 package.


%package extras-libclang-cpp
Summary: extras-libclang-cpp components for the llvm13 package.
Group: Default

%description extras-libclang-cpp
extras-libclang-cpp components for the llvm13 package.


%package extras-libllvm
Summary: extras-libllvm components for the llvm13 package.
Group: Default

%description extras-libllvm
extras-libllvm components for the llvm13 package.


%package lib
Summary: lib components for the llvm13 package.
Group: Libraries
Requires: llvm13-license = %{version}-%{release}

%description lib
lib components for the llvm13 package.


%package lib32
Summary: lib32 components for the llvm13 package.
Group: Default
Requires: llvm13-license = %{version}-%{release}

%description lib32
lib32 components for the llvm13 package.


%package license
Summary: license components for the llvm13 package.
Group: Default

%description license
license components for the llvm13 package.


%package python
Summary: python components for the llvm13 package.
Group: Default
Requires: llvm13-python3 = %{version}-%{release}

%description python
python components for the llvm13 package.


%package python3
Summary: python3 components for the llvm13 package.
Group: Default
Requires: python3-core
Requires: pypi(ptyprocess)

%description python3
python3 components for the llvm13 package.


%package staticdev32
Summary: staticdev32 components for the llvm13 package.
Group: Default
Requires: llvm13-dev = %{version}-%{release}

%description staticdev32
staticdev32 components for the llvm13 package.


%prep
%setup -q -n llvm-project-13.0.0.src
cd %{_builddir}
tar xf %{_sourcedir}/v13.0.0.tar.gz
cd %{_builddir}
tar xf %{_sourcedir}/92f21c9b214178ce67cf1e31a00a33312590403a.tar.gz
cd %{_builddir}/llvm-project-13.0.0.src
mkdir -p llvm/projects/SPIRV-LLVM-Translator
cp -r %{_builddir}/SPIRV-LLVM-Translator-13.0.0/* %{_builddir}/llvm-project-13.0.0.src/llvm/projects/SPIRV-LLVM-Translator
mkdir -p llvm/projects/SPIRV-Headers
cp -r %{_builddir}/SPIRV-Headers-92f21c9b214178ce67cf1e31a00a33312590403a/* %{_builddir}/llvm-project-13.0.0.src/llvm/projects/SPIRV-Headers
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1

%build
## build_prepend_once content
# Bootstrap Clang and the table generators
# See https://build.opensuse.org/package/view_file/devel:tools:compiler/llvm10/llvm10.spec?expand=1
pushd llvm
mkdir clr-bootstrap-build
pushd clr-bootstrap-build
CFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CFLAGS` -fno-integrated-as"
CXXFLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//; s/-feliminate-unused-debug-types//' <<<$CXXFLAGS` -fno-integrated-as"
%cmake .. \
-G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_C_COMPILER=clang \
-DCMAKE_C_FLAGS="$CFLAGS -g0" \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_CXX_FLAGS="$CXXFLAGS -g0" \
-DLLVM_ENABLE_PROJECTS="clang;llvm-tblgen;clang-tblgen" \
-DLLVM_BUILD_LLVM_DYLIB:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=OFF \
-DLLVM_ENABLE_ASSERTIONS=OFF \
-DLLVM_TARGETS_TO_BUILD=Native \
-DCLANG_ENABLE_ARCMT:BOOL=OFF \
-DCLANG_ENABLE_STATIC_ANALYZER:BOOL=OFF \
-DCMAKE_SKIP_RPATH:BOOL=OFF \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3
ninja -v
popd
export PATH=/usr/lib64/ccache/bin/:${PWD}/clr-bootstrap-build/bin:${PATH}
export LLVM_AR=${PWD}/clr-bootstrap-build/bin/llvm-ar
export LLVM_RANLIB=${PWD}/clr-bootstrap-build/bin/llvm-ranlib
export LLVM_TABLEGEN=${PWD}/clr-bootstrap-build/bin/llvm-tblgen
export CLANG_TABLEGEN=${PWD}/clr-bootstrap-build/bin/clang-tblgen
popd
## build_prepend_once end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650487174
unset LD_AS_NEEDED
pushd llvm
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
export FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export FCFLAGS=$FFLAGS
unset LDFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -G Ninja \
-DCMAKE_C_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CFLAGS`" \
-DCMAKE_CXX_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CXXFLAGS`" \
-DCMAKE_EXE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_MODULE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_SHARED_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DENABLE_LINKER_BUILD_ID=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
-DCLANG_LINK_CLANG_DYLIB:BOOL=ON \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=ON \
-DLLVM_ENABLE_FFI:BOOL=ON -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DLLVM_TABLEGEN=$LLVM_TABLEGEN \
-DCLANG_TABLEGEN=$CLANG_TABLEGEN \
-DLLVM_ENABLE_PROJECTS="lld;lldb;clang;clang-tools-extra;compiler-rt;openmp;polly;mler;" \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
`case "$PWD" in *build32) \
echo -DLLVM_BUILD_TOOLS:BOOL=OFF -DLLVM_TOOL_CLANG_BUILD:BOOL=OFF; \
echo -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=OFF -DLLVM_TOOL_LLD_BUILD:BOOL=OFF; \
echo -DLLVM_TOOL_OPENMP_BUILD:BOOL=OFF -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=OFF; \
echo -DLLVM_LIBDIR_SUFFIX=32 -DLLVM_HOST_TRIPLE="i686-generic-linux"; \
echo -DLLVM_ENABLE_PROJECTS="clang" \
;; \
esac`
ninja  %{?_smp_mflags}
popd
mkdir -p clr-build32
pushd clr-build32
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CFLAGS=${CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CXXFLAGS=${CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
export FFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export FCFLAGS=$FFLAGS
unset LDFLAGS
unset LDFLAGS
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%cmake -DLIB_INSTALL_DIR:PATH=/usr/lib32 -DCMAKE_INSTALL_LIBDIR=/usr/lib32 -DLIB_SUFFIX=32 .. -G Ninja \
-DCMAKE_C_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CFLAGS`" \
-DCMAKE_CXX_FLAGS="`sed -E 's/-Wl,\S+\s//g; s/-Wp,-D_FORTIFY_SOURCE=2//' <<<$CXXFLAGS`" \
-DCMAKE_EXE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_MODULE_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DCMAKE_SHARED_LINKER_FLAGS="$CXXFLAGS -Wl,--as-needed -Wl,--build-id=sha1" \
-DENABLE_LINKER_BUILD_ID=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DLLVM_LINK_LLVM_DYLIB:BOOL=ON \
-DCLANG_LINK_CLANG_DYLIB:BOOL=ON \
-DLLVM_BUILD_RUNTIME:BOOL=ON \
-DLLVM_BUILD_TOOLS:BOOL=ON \
-DLLVM_ENABLE_FFI:BOOL=ON -DFFI_INCLUDE_DIR=`pkg-config --variable=includedir libffi` \
-DLLVM_ENABLE_RTTI:BOOL=ON \
-DLLVM_ENABLE_ZLIB:BOOL=ON \
-DLLVM_REQUIRES_RTTI:BOOL=ON \
-DLLVM_TABLEGEN=$LLVM_TABLEGEN \
-DCLANG_TABLEGEN=$CLANG_TABLEGEN \
-DLLVM_ENABLE_PROJECTS="lld;lldb;clang;clang-tools-extra;compiler-rt;openmp;polly;mler;" \
-DLLVM_LIBDIR_SUFFIX=64 \
-DLLVM_BINUTILS_INCDIR=/usr/include \
-DLLVM_HOST_TRIPLE="x86_64-generic-linux" \
-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
`case "$PWD" in *build32) \
echo -DLLVM_BUILD_TOOLS:BOOL=OFF -DLLVM_TOOL_CLANG_BUILD:BOOL=OFF; \
echo -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=OFF -DLLVM_TOOL_LLD_BUILD:BOOL=OFF; \
echo -DLLVM_TOOL_OPENMP_BUILD:BOOL=OFF -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=OFF; \
echo -DLLVM_LIBDIR_SUFFIX=32 -DLLVM_HOST_TRIPLE="i686-generic-linux"; \
echo -DLLVM_ENABLE_PROJECTS="clang" \
;; \
esac`
ninja  %{?_smp_mflags}
unset PKG_CONFIG_PATH
popd
popd

%install
export SOURCE_DATE_EPOCH=1650487174
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/llvm13
cp %{_builddir}/SPIRV-Headers-92f21c9b214178ce67cf1e31a00a33312590403a/LICENSE %{buildroot}/usr/share/package-licenses/llvm13/9a84200f47e09abfbde1a6b25028460451b23d03
cp %{_builddir}/SPIRV-LLVM-Translator-13.0.0/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/8f178caf2a2d6e6c711a30da69077572df356cf6
cp %{_builddir}/llvm-project-13.0.0.src/clang-tools-extra/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/a1691103171dc1d21cfa85f1d4809a16b9f1367f
cp %{_builddir}/llvm-project-13.0.0.src/clang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/a1691103171dc1d21cfa85f1d4809a16b9f1367f
cp %{_builddir}/llvm-project-13.0.0.src/clang/tools/clang-format-vs/ClangFormat/license.txt %{buildroot}/usr/share/package-licenses/llvm13/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
cp %{_builddir}/llvm-project-13.0.0.src/compiler-rt/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b
cp %{_builddir}/llvm-project-13.0.0.src/cross-project-tests/debuginfo-tests/dexter/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm13/af07f365643f841c69797e9059b66f0bd847f1cd
cp %{_builddir}/llvm-project-13.0.0.src/flang/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/85c0f2884378413881b4d3e27fc24b220f71889b
cp %{_builddir}/llvm-project-13.0.0.src/libc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/a1691103171dc1d21cfa85f1d4809a16b9f1367f
cp %{_builddir}/llvm-project-13.0.0.src/libclc/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/8737af83de0d40386dca9a4abe2b6faa83cb4750
cp %{_builddir}/llvm-project-13.0.0.src/libcxx/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/7b75a5471af8b3d49e60df0a5d72f95ea8214231
cp %{_builddir}/llvm-project-13.0.0.src/libcxx/utils/google-benchmark/LICENSE %{buildroot}/usr/share/package-licenses/llvm13/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/llvm-project-13.0.0.src/libcxxabi/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/11156021d878bfcbdf2563b4f65db32b4d9f92a3
cp %{_builddir}/llvm-project-13.0.0.src/libunwind/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/d79062af10a33188d4a74d976323845a2cf9023d
cp %{_builddir}/llvm-project-13.0.0.src/lld/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
cp %{_builddir}/llvm-project-13.0.0.src/lldb/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
cp %{_builddir}/llvm-project-13.0.0.src/lldb/third_party/Python/module/pexpect-4.6/LICENSE %{buildroot}/usr/share/package-licenses/llvm13/5a99e7077ee89ba92fb3f584855e8970096cd5dc
cp %{_builddir}/llvm-project-13.0.0.src/lldb/third_party/Python/module/ptyprocess-0.6.0/LICENSE %{buildroot}/usr/share/package-licenses/llvm13/db1f866b29c6a191752c7c5924b7572cdbc47c34
cp %{_builddir}/llvm-project-13.0.0.src/lldb/third_party/Python/module/six/LICENSE %{buildroot}/usr/share/package-licenses/llvm13/f226af67862c0c7a0e921e24672a3a1375691e3e
cp %{_builddir}/llvm-project-13.0.0.src/llvm/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/af07f365643f841c69797e9059b66f0bd847f1cd
cp %{_builddir}/llvm-project-13.0.0.src/llvm/test/YAMLParser/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm13/c01c212bdf3925189f673e2081b44094023860ea
cp %{_builddir}/llvm-project-13.0.0.src/llvm/tools/msbuild/license.txt %{buildroot}/usr/share/package-licenses/llvm13/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
cp %{_builddir}/llvm-project-13.0.0.src/llvm/utils/benchmark/LICENSE %{buildroot}/usr/share/package-licenses/llvm13/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/llvm-project-13.0.0.src/llvm/utils/lit/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/af07f365643f841c69797e9059b66f0bd847f1cd
cp %{_builddir}/llvm-project-13.0.0.src/llvm/utils/unittest/googlemock/LICENSE.txt %{buildroot}/usr/share/package-licenses/llvm13/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/llvm-project-13.0.0.src/llvm/utils/unittest/googletest/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/5a2314153eadadc69258a9429104cd11804ea304
cp %{_builddir}/llvm-project-13.0.0.src/mlir/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/85c0f2884378413881b4d3e27fc24b220f71889b
cp %{_builddir}/llvm-project-13.0.0.src/openmp/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/e3cccabb67bd491a643d32a7d2b65b49836e626d
cp %{_builddir}/llvm-project-13.0.0.src/parallel-libs/acxxel/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/a1691103171dc1d21cfa85f1d4809a16b9f1367f
cp %{_builddir}/llvm-project-13.0.0.src/polly/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/8d3b142938f83e7045951089b52676a5605eee37
cp %{_builddir}/llvm-project-13.0.0.src/polly/lib/External/isl/LICENSE %{buildroot}/usr/share/package-licenses/llvm13/45c2429b5881295597e96c81fc50f7b8a42e769f
cp %{_builddir}/llvm-project-13.0.0.src/polly/tools/GPURuntime/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/ce27417c74ca5ad6d0b5c96ede8ff82e4d87900f
cp %{_builddir}/llvm-project-13.0.0.src/pstl/LICENSE.TXT %{buildroot}/usr/share/package-licenses/llvm13/72c865be698cefc46549ed61e279f98432364fca
pushd llvm
pushd clr-build32
%ninja_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd clr-build
%ninja_install
popd
popd
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/libgomp.so
rm -f %{buildroot}*/usr/lib64/TestPlugin.so
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports.cmake
rm -f %{buildroot}*/usr/lib64/cmake/llvm/LLVMStaticExports-relwithdebinfo.cmake
rm -f %{buildroot}*/usr/lib64/pkgconfig/LLVMSPIRVLib.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/SPIRV-Headers.pc
rm -f %{buildroot}*/usr/lib64/pkgconfig/'32*.pc'
rm -f %{buildroot}*/usr/lib/python3.10/site-packages/six.py
## install_append content
# remove libomptarget.rtl.amdgpu.so for now
# it is built using rpath and wants to be in the wrong path
rm -f %{buildroot}/usr/lib/libomptarget.rtl.amdgpu.so

# Rename the Gold plugin elsewhere, as we're erasing *.so below
mv %{buildroot}/usr/lib64/LLVMgold.so %{buildroot}/usr/lib64/LLVMgold.so.save

# Remove files that should come from the main llvm package
rm -rf %{buildroot}/usr/include
rm -rf %{buildroot}/usr/lib64/*.a
rm -rf %{buildroot}/usr/lib64/*.so
rm -rf %{buildroot}/usr/lib64/cmake
rm -rf %{buildroot}/usr/lib64/pkgconfig
rm -rf %{buildroot}/usr/libexec

mv %{buildroot}/usr/share/package-licenses %{buildroot}/usr/
rm -rf %{buildroot}/usr/share/*
mv %{buildroot}/usr/package-licenses %{buildroot}/usr/share

# Rename the tools to have a versioned suffix and symlink back
pushd %{buildroot}/usr
FULL_VERSION=%{version}
VERSION=${FULL_VERSION%%%%.*}
mkdir -p lib64/clang/$FULL_VERSION/bin
mv bin/* lib64/clang/$FULL_VERSION/bin
for f in lib64/clang/$FULL_VERSION/bin/*; do
case "$f" in
*-$VERSION)
# Already versioned, leave it alone
continue
;;
esac
ln -s ../$f bin/${f##*/}-$VERSION
done

# libclang-cpp auto-relocates, so create a symlink so it finds its files
ln -s ../.. lib64/clang/$FULL_VERSION/lib64

# Put the LLVM gold plugin back, under the versioned name
mv lib64/LLVMgold.so.save lib64/LLVMgold-$VERSION.so
mkdir -p lib/bfd-plugins
ln -s ../../lib64/LLVMgold-$VERSION.so lib/bfd-plugins
popd
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/libear/__init__.py
/usr/lib/libear/config.h.in
/usr/lib/libear/ear.c
/usr/lib/libscanbuild/__init__.py
/usr/lib/libscanbuild/analyze.py
/usr/lib/libscanbuild/arguments.py
/usr/lib/libscanbuild/clang.py
/usr/lib/libscanbuild/compilation.py
/usr/lib/libscanbuild/intercept.py
/usr/lib/libscanbuild/report.py
/usr/lib/libscanbuild/resources/scanview.css
/usr/lib/libscanbuild/resources/selectable.js
/usr/lib/libscanbuild/resources/sorttable.js
/usr/lib/libscanbuild/shell.py
/usr/lib32/clang/13.0.0/include/cuda_wrappers/algorithm
/usr/lib32/clang/13.0.0/include/cuda_wrappers/complex
/usr/lib32/clang/13.0.0/include/cuda_wrappers/new
/usr/lib32/clang/13.0.0/include/module.modulemap
/usr/lib32/clang/13.0.0/include/openmp_wrappers/cmath
/usr/lib32/clang/13.0.0/include/openmp_wrappers/complex
/usr/lib32/clang/13.0.0/include/openmp_wrappers/new
/usr/lib64/clang/13.0.0/bin/analyze-build
/usr/lib64/clang/13.0.0/bin/bugpoint
/usr/lib64/clang/13.0.0/bin/c-index-test
/usr/lib64/clang/13.0.0/bin/clang
/usr/lib64/clang/13.0.0/bin/clang++
/usr/lib64/clang/13.0.0/bin/clang-13
/usr/lib64/clang/13.0.0/bin/clang-apply-replacements
/usr/lib64/clang/13.0.0/bin/clang-change-namespace
/usr/lib64/clang/13.0.0/bin/clang-check
/usr/lib64/clang/13.0.0/bin/clang-cl
/usr/lib64/clang/13.0.0/bin/clang-cpp
/usr/lib64/clang/13.0.0/bin/clang-doc
/usr/lib64/clang/13.0.0/bin/clang-extdef-mapping
/usr/lib64/clang/13.0.0/bin/clang-format
/usr/lib64/clang/13.0.0/bin/clang-include-fixer
/usr/lib64/clang/13.0.0/bin/clang-move
/usr/lib64/clang/13.0.0/bin/clang-offload-bundler
/usr/lib64/clang/13.0.0/bin/clang-offload-wrapper
/usr/lib64/clang/13.0.0/bin/clang-query
/usr/lib64/clang/13.0.0/bin/clang-refactor
/usr/lib64/clang/13.0.0/bin/clang-rename
/usr/lib64/clang/13.0.0/bin/clang-reorder-fields
/usr/lib64/clang/13.0.0/bin/clang-repl
/usr/lib64/clang/13.0.0/bin/clang-scan-deps
/usr/lib64/clang/13.0.0/bin/clang-tidy
/usr/lib64/clang/13.0.0/bin/clangd
/usr/lib64/clang/13.0.0/bin/diagtool
/usr/lib64/clang/13.0.0/bin/dsymutil
/usr/lib64/clang/13.0.0/bin/find-all-symbols
/usr/lib64/clang/13.0.0/bin/git-clang-format
/usr/lib64/clang/13.0.0/bin/hmaptool
/usr/lib64/clang/13.0.0/bin/hwasan_symbolize
/usr/lib64/clang/13.0.0/bin/intercept-build
/usr/lib64/clang/13.0.0/bin/ld.lld
/usr/lib64/clang/13.0.0/bin/ld64.lld
/usr/lib64/clang/13.0.0/bin/ld64.lld.darwinnew
/usr/lib64/clang/13.0.0/bin/ld64.lld.darwinold
/usr/lib64/clang/13.0.0/bin/llc
/usr/lib64/clang/13.0.0/bin/lld
/usr/lib64/clang/13.0.0/bin/lld-link
/usr/lib64/clang/13.0.0/bin/lldb
/usr/lib64/clang/13.0.0/bin/lldb-argdumper
/usr/lib64/clang/13.0.0/bin/lldb-instr
/usr/lib64/clang/13.0.0/bin/lldb-server
/usr/lib64/clang/13.0.0/bin/lldb-vscode
/usr/lib64/clang/13.0.0/bin/lli
/usr/lib64/clang/13.0.0/bin/llvm-addr2line
/usr/lib64/clang/13.0.0/bin/llvm-ar
/usr/lib64/clang/13.0.0/bin/llvm-as
/usr/lib64/clang/13.0.0/bin/llvm-bcanalyzer
/usr/lib64/clang/13.0.0/bin/llvm-bitcode-strip
/usr/lib64/clang/13.0.0/bin/llvm-c-test
/usr/lib64/clang/13.0.0/bin/llvm-cat
/usr/lib64/clang/13.0.0/bin/llvm-cfi-verify
/usr/lib64/clang/13.0.0/bin/llvm-config
/usr/lib64/clang/13.0.0/bin/llvm-cov
/usr/lib64/clang/13.0.0/bin/llvm-cvtres
/usr/lib64/clang/13.0.0/bin/llvm-cxxdump
/usr/lib64/clang/13.0.0/bin/llvm-cxxfilt
/usr/lib64/clang/13.0.0/bin/llvm-cxxmap
/usr/lib64/clang/13.0.0/bin/llvm-diff
/usr/lib64/clang/13.0.0/bin/llvm-dis
/usr/lib64/clang/13.0.0/bin/llvm-dlltool
/usr/lib64/clang/13.0.0/bin/llvm-dwarfdump
/usr/lib64/clang/13.0.0/bin/llvm-dwp
/usr/lib64/clang/13.0.0/bin/llvm-exegesis
/usr/lib64/clang/13.0.0/bin/llvm-extract
/usr/lib64/clang/13.0.0/bin/llvm-gsymutil
/usr/lib64/clang/13.0.0/bin/llvm-ifs
/usr/lib64/clang/13.0.0/bin/llvm-install-name-tool
/usr/lib64/clang/13.0.0/bin/llvm-jitlink
/usr/lib64/clang/13.0.0/bin/llvm-lib
/usr/lib64/clang/13.0.0/bin/llvm-libtool-darwin
/usr/lib64/clang/13.0.0/bin/llvm-link
/usr/lib64/clang/13.0.0/bin/llvm-lipo
/usr/lib64/clang/13.0.0/bin/llvm-lto
/usr/lib64/clang/13.0.0/bin/llvm-lto2
/usr/lib64/clang/13.0.0/bin/llvm-mc
/usr/lib64/clang/13.0.0/bin/llvm-mca
/usr/lib64/clang/13.0.0/bin/llvm-ml
/usr/lib64/clang/13.0.0/bin/llvm-modextract
/usr/lib64/clang/13.0.0/bin/llvm-mt
/usr/lib64/clang/13.0.0/bin/llvm-nm
/usr/lib64/clang/13.0.0/bin/llvm-objcopy
/usr/lib64/clang/13.0.0/bin/llvm-objdump
/usr/lib64/clang/13.0.0/bin/llvm-omp-device-info
/usr/lib64/clang/13.0.0/bin/llvm-opt-report
/usr/lib64/clang/13.0.0/bin/llvm-otool
/usr/lib64/clang/13.0.0/bin/llvm-pdbutil
/usr/lib64/clang/13.0.0/bin/llvm-profdata
/usr/lib64/clang/13.0.0/bin/llvm-profgen
/usr/lib64/clang/13.0.0/bin/llvm-ranlib
/usr/lib64/clang/13.0.0/bin/llvm-rc
/usr/lib64/clang/13.0.0/bin/llvm-readelf
/usr/lib64/clang/13.0.0/bin/llvm-readobj
/usr/lib64/clang/13.0.0/bin/llvm-reduce
/usr/lib64/clang/13.0.0/bin/llvm-rtdyld
/usr/lib64/clang/13.0.0/bin/llvm-sim
/usr/lib64/clang/13.0.0/bin/llvm-size
/usr/lib64/clang/13.0.0/bin/llvm-spirv
/usr/lib64/clang/13.0.0/bin/llvm-split
/usr/lib64/clang/13.0.0/bin/llvm-stress
/usr/lib64/clang/13.0.0/bin/llvm-strings
/usr/lib64/clang/13.0.0/bin/llvm-strip
/usr/lib64/clang/13.0.0/bin/llvm-symbolizer
/usr/lib64/clang/13.0.0/bin/llvm-tapi-diff
/usr/lib64/clang/13.0.0/bin/llvm-tblgen
/usr/lib64/clang/13.0.0/bin/llvm-undname
/usr/lib64/clang/13.0.0/bin/llvm-windres
/usr/lib64/clang/13.0.0/bin/llvm-xray
/usr/lib64/clang/13.0.0/bin/modularize
/usr/lib64/clang/13.0.0/bin/opt
/usr/lib64/clang/13.0.0/bin/pp-trace
/usr/lib64/clang/13.0.0/bin/run-clang-tidy
/usr/lib64/clang/13.0.0/bin/sancov
/usr/lib64/clang/13.0.0/bin/sanstats
/usr/lib64/clang/13.0.0/bin/scan-build
/usr/lib64/clang/13.0.0/bin/scan-build-py
/usr/lib64/clang/13.0.0/bin/scan-view
/usr/lib64/clang/13.0.0/bin/split-file
/usr/lib64/clang/13.0.0/bin/verify-uselistorder
/usr/lib64/clang/13.0.0/bin/wasm-ld
/usr/lib64/clang/13.0.0/include/cuda_wrappers/algorithm
/usr/lib64/clang/13.0.0/include/cuda_wrappers/complex
/usr/lib64/clang/13.0.0/include/cuda_wrappers/new
/usr/lib64/clang/13.0.0/include/module.modulemap
/usr/lib64/clang/13.0.0/include/openmp_wrappers/cmath
/usr/lib64/clang/13.0.0/include/openmp_wrappers/complex
/usr/lib64/clang/13.0.0/include/openmp_wrappers/new
/usr/lib64/clang/13.0.0/include/profile/InstrProfData.inc
/usr/lib64/clang/13.0.0/lib/linux/clang_rt.crtbegin-i386.o
/usr/lib64/clang/13.0.0/lib/linux/clang_rt.crtbegin-x86_64.o
/usr/lib64/clang/13.0.0/lib/linux/clang_rt.crtend-i386.o
/usr/lib64/clang/13.0.0/lib/linux/clang_rt.crtend-x86_64.o
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan-preinit-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan-preinit-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan_cxx-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan_cxx-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.builtins-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.builtins-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.cfi-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.cfi-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.cfi_diag-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.cfi_diag-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.dd-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.dfsan-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.dfsan-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.fuzzer-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.fuzzer-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.fuzzer_interceptors-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.fuzzer_interceptors-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.fuzzer_no_main-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.gwp_asan-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.gwp_asan-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan_aliases-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan_aliases-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan_aliases_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan_aliases_cxx-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan_cxx-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.lsan-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.lsan-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.memprof-preinit-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.memprof-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.memprof-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.memprof_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.memprof_cxx-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.msan-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.msan-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.msan_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.msan_cxx-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.orc-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.profile-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.profile-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.safestack-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.safestack-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_cxx-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_cxx_minimal-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_cxx_minimal-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_minimal-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_minimal-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_standalone-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_standalone-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_standalone_cxx-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_standalone_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.stats-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.stats-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.stats_client-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.stats_client-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.tsan-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.tsan-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.tsan_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.tsan_cxx-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_minimal-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_minimal-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_minimal-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone_cxx-i386.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone_cxx-x86_64.a.syms
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.xray-basic-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.xray-fdr-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.xray-profiling-x86_64.a
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.xray-x86_64.a
/usr/lib64/clang/13.0.0/lib64
/usr/lib64/clang/13.0.0/share/asan_ignorelist.txt
/usr/lib64/clang/13.0.0/share/cfi_ignorelist.txt
/usr/lib64/clang/13.0.0/share/dfsan_abilist.txt
/usr/lib64/clang/13.0.0/share/hwasan_ignorelist.txt
/usr/lib64/clang/13.0.0/share/msan_ignorelist.txt
/usr/lib64/libomptarget-amdgcn-gfx700.bc
/usr/lib64/libomptarget-amdgcn-gfx701.bc
/usr/lib64/libomptarget-amdgcn-gfx801.bc
/usr/lib64/libomptarget-amdgcn-gfx803.bc
/usr/lib64/libomptarget-amdgcn-gfx900.bc
/usr/lib64/libomptarget-amdgcn-gfx902.bc
/usr/lib64/libomptarget-amdgcn-gfx906.bc
/usr/lib64/libomptarget-amdgcn-gfx908.bc

%files bin
%defattr(-,root,root,-)
/usr/bin/analyze-build-13
/usr/bin/bugpoint-13
/usr/bin/c-index-test-13
/usr/bin/clang++-13
/usr/bin/clang-13
/usr/bin/clang-apply-replacements-13
/usr/bin/clang-change-namespace-13
/usr/bin/clang-check-13
/usr/bin/clang-cl-13
/usr/bin/clang-cpp-13
/usr/bin/clang-doc-13
/usr/bin/clang-extdef-mapping-13
/usr/bin/clang-format-13
/usr/bin/clang-include-fixer-13
/usr/bin/clang-move-13
/usr/bin/clang-offload-bundler-13
/usr/bin/clang-offload-wrapper-13
/usr/bin/clang-query-13
/usr/bin/clang-refactor-13
/usr/bin/clang-rename-13
/usr/bin/clang-reorder-fields-13
/usr/bin/clang-repl-13
/usr/bin/clang-scan-deps-13
/usr/bin/clang-tidy-13
/usr/bin/clangd-13
/usr/bin/diagtool-13
/usr/bin/dsymutil-13
/usr/bin/find-all-symbols-13
/usr/bin/git-clang-format-13
/usr/bin/hmaptool-13
/usr/bin/hwasan_symbolize-13
/usr/bin/intercept-build-13
/usr/bin/ld.lld-13
/usr/bin/ld64.lld-13
/usr/bin/ld64.lld.darwinnew-13
/usr/bin/ld64.lld.darwinold-13
/usr/bin/llc-13
/usr/bin/lld-13
/usr/bin/lld-link-13
/usr/bin/lldb-13
/usr/bin/lldb-argdumper-13
/usr/bin/lldb-instr-13
/usr/bin/lldb-server-13
/usr/bin/lldb-vscode-13
/usr/bin/lli-13
/usr/bin/llvm-addr2line-13
/usr/bin/llvm-ar-13
/usr/bin/llvm-as-13
/usr/bin/llvm-bcanalyzer-13
/usr/bin/llvm-bitcode-strip-13
/usr/bin/llvm-c-test-13
/usr/bin/llvm-cat-13
/usr/bin/llvm-cfi-verify-13
/usr/bin/llvm-config-13
/usr/bin/llvm-cov-13
/usr/bin/llvm-cvtres-13
/usr/bin/llvm-cxxdump-13
/usr/bin/llvm-cxxfilt-13
/usr/bin/llvm-cxxmap-13
/usr/bin/llvm-diff-13
/usr/bin/llvm-dis-13
/usr/bin/llvm-dlltool-13
/usr/bin/llvm-dwarfdump-13
/usr/bin/llvm-dwp-13
/usr/bin/llvm-exegesis-13
/usr/bin/llvm-extract-13
/usr/bin/llvm-gsymutil-13
/usr/bin/llvm-ifs-13
/usr/bin/llvm-install-name-tool-13
/usr/bin/llvm-jitlink-13
/usr/bin/llvm-lib-13
/usr/bin/llvm-libtool-darwin-13
/usr/bin/llvm-link-13
/usr/bin/llvm-lipo-13
/usr/bin/llvm-lto-13
/usr/bin/llvm-lto2-13
/usr/bin/llvm-mc-13
/usr/bin/llvm-mca-13
/usr/bin/llvm-ml-13
/usr/bin/llvm-modextract-13
/usr/bin/llvm-mt-13
/usr/bin/llvm-nm-13
/usr/bin/llvm-objcopy-13
/usr/bin/llvm-objdump-13
/usr/bin/llvm-omp-device-info-13
/usr/bin/llvm-opt-report-13
/usr/bin/llvm-otool-13
/usr/bin/llvm-pdbutil-13
/usr/bin/llvm-profdata-13
/usr/bin/llvm-profgen-13
/usr/bin/llvm-ranlib-13
/usr/bin/llvm-rc-13
/usr/bin/llvm-readelf-13
/usr/bin/llvm-readobj-13
/usr/bin/llvm-reduce-13
/usr/bin/llvm-rtdyld-13
/usr/bin/llvm-sim-13
/usr/bin/llvm-size-13
/usr/bin/llvm-spirv-13
/usr/bin/llvm-split-13
/usr/bin/llvm-stress-13
/usr/bin/llvm-strings-13
/usr/bin/llvm-strip-13
/usr/bin/llvm-symbolizer-13
/usr/bin/llvm-tapi-diff-13
/usr/bin/llvm-tblgen-13
/usr/bin/llvm-undname-13
/usr/bin/llvm-windres-13
/usr/bin/llvm-xray-13
/usr/bin/modularize-13
/usr/bin/opt-13
/usr/bin/pp-trace-13
/usr/bin/run-clang-tidy-13
/usr/bin/sancov-13
/usr/bin/sanstats-13
/usr/bin/scan-build-13
/usr/bin/scan-build-py-13
/usr/bin/scan-view-13
/usr/bin/split-file-13
/usr/bin/verify-uselistorder-13
/usr/bin/wasm-ld-13

%files dev
%defattr(-,root,root,-)
/usr/lib32/clang/13.0.0/include/__clang_cuda_builtin_vars.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_cmath.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_complex_builtins.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_device_functions.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_intrinsics.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_libdevice_declares.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_math.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_math_forward_declares.h
/usr/lib32/clang/13.0.0/include/__clang_cuda_runtime_wrapper.h
/usr/lib32/clang/13.0.0/include/__clang_hip_cmath.h
/usr/lib32/clang/13.0.0/include/__clang_hip_libdevice_declares.h
/usr/lib32/clang/13.0.0/include/__clang_hip_math.h
/usr/lib32/clang/13.0.0/include/__clang_hip_runtime_wrapper.h
/usr/lib32/clang/13.0.0/include/__stddef_max_align_t.h
/usr/lib32/clang/13.0.0/include/__wmmintrin_aes.h
/usr/lib32/clang/13.0.0/include/__wmmintrin_pclmul.h
/usr/lib32/clang/13.0.0/include/adxintrin.h
/usr/lib32/clang/13.0.0/include/altivec.h
/usr/lib32/clang/13.0.0/include/ammintrin.h
/usr/lib32/clang/13.0.0/include/amxintrin.h
/usr/lib32/clang/13.0.0/include/arm64intr.h
/usr/lib32/clang/13.0.0/include/arm_acle.h
/usr/lib32/clang/13.0.0/include/arm_bf16.h
/usr/lib32/clang/13.0.0/include/arm_cde.h
/usr/lib32/clang/13.0.0/include/arm_cmse.h
/usr/lib32/clang/13.0.0/include/arm_fp16.h
/usr/lib32/clang/13.0.0/include/arm_mve.h
/usr/lib32/clang/13.0.0/include/arm_neon.h
/usr/lib32/clang/13.0.0/include/arm_sve.h
/usr/lib32/clang/13.0.0/include/armintr.h
/usr/lib32/clang/13.0.0/include/avx2intrin.h
/usr/lib32/clang/13.0.0/include/avx512bf16intrin.h
/usr/lib32/clang/13.0.0/include/avx512bitalgintrin.h
/usr/lib32/clang/13.0.0/include/avx512bwintrin.h
/usr/lib32/clang/13.0.0/include/avx512cdintrin.h
/usr/lib32/clang/13.0.0/include/avx512dqintrin.h
/usr/lib32/clang/13.0.0/include/avx512erintrin.h
/usr/lib32/clang/13.0.0/include/avx512fintrin.h
/usr/lib32/clang/13.0.0/include/avx512ifmaintrin.h
/usr/lib32/clang/13.0.0/include/avx512ifmavlintrin.h
/usr/lib32/clang/13.0.0/include/avx512pfintrin.h
/usr/lib32/clang/13.0.0/include/avx512vbmi2intrin.h
/usr/lib32/clang/13.0.0/include/avx512vbmiintrin.h
/usr/lib32/clang/13.0.0/include/avx512vbmivlintrin.h
/usr/lib32/clang/13.0.0/include/avx512vlbf16intrin.h
/usr/lib32/clang/13.0.0/include/avx512vlbitalgintrin.h
/usr/lib32/clang/13.0.0/include/avx512vlbwintrin.h
/usr/lib32/clang/13.0.0/include/avx512vlcdintrin.h
/usr/lib32/clang/13.0.0/include/avx512vldqintrin.h
/usr/lib32/clang/13.0.0/include/avx512vlintrin.h
/usr/lib32/clang/13.0.0/include/avx512vlvbmi2intrin.h
/usr/lib32/clang/13.0.0/include/avx512vlvnniintrin.h
/usr/lib32/clang/13.0.0/include/avx512vlvp2intersectintrin.h
/usr/lib32/clang/13.0.0/include/avx512vnniintrin.h
/usr/lib32/clang/13.0.0/include/avx512vp2intersectintrin.h
/usr/lib32/clang/13.0.0/include/avx512vpopcntdqintrin.h
/usr/lib32/clang/13.0.0/include/avx512vpopcntdqvlintrin.h
/usr/lib32/clang/13.0.0/include/avxintrin.h
/usr/lib32/clang/13.0.0/include/avxvnniintrin.h
/usr/lib32/clang/13.0.0/include/bmi2intrin.h
/usr/lib32/clang/13.0.0/include/bmiintrin.h
/usr/lib32/clang/13.0.0/include/builtins.h
/usr/lib32/clang/13.0.0/include/cet.h
/usr/lib32/clang/13.0.0/include/cetintrin.h
/usr/lib32/clang/13.0.0/include/cldemoteintrin.h
/usr/lib32/clang/13.0.0/include/clflushoptintrin.h
/usr/lib32/clang/13.0.0/include/clwbintrin.h
/usr/lib32/clang/13.0.0/include/clzerointrin.h
/usr/lib32/clang/13.0.0/include/cpuid.h
/usr/lib32/clang/13.0.0/include/emmintrin.h
/usr/lib32/clang/13.0.0/include/enqcmdintrin.h
/usr/lib32/clang/13.0.0/include/f16cintrin.h
/usr/lib32/clang/13.0.0/include/float.h
/usr/lib32/clang/13.0.0/include/fma4intrin.h
/usr/lib32/clang/13.0.0/include/fmaintrin.h
/usr/lib32/clang/13.0.0/include/fxsrintrin.h
/usr/lib32/clang/13.0.0/include/gfniintrin.h
/usr/lib32/clang/13.0.0/include/hexagon_circ_brev_intrinsics.h
/usr/lib32/clang/13.0.0/include/hexagon_protos.h
/usr/lib32/clang/13.0.0/include/hexagon_types.h
/usr/lib32/clang/13.0.0/include/hresetintrin.h
/usr/lib32/clang/13.0.0/include/htmintrin.h
/usr/lib32/clang/13.0.0/include/htmxlintrin.h
/usr/lib32/clang/13.0.0/include/hvx_hexagon_protos.h
/usr/lib32/clang/13.0.0/include/ia32intrin.h
/usr/lib32/clang/13.0.0/include/immintrin.h
/usr/lib32/clang/13.0.0/include/intrin.h
/usr/lib32/clang/13.0.0/include/inttypes.h
/usr/lib32/clang/13.0.0/include/invpcidintrin.h
/usr/lib32/clang/13.0.0/include/iso646.h
/usr/lib32/clang/13.0.0/include/keylockerintrin.h
/usr/lib32/clang/13.0.0/include/limits.h
/usr/lib32/clang/13.0.0/include/lwpintrin.h
/usr/lib32/clang/13.0.0/include/lzcntintrin.h
/usr/lib32/clang/13.0.0/include/mm3dnow.h
/usr/lib32/clang/13.0.0/include/mm_malloc.h
/usr/lib32/clang/13.0.0/include/mmintrin.h
/usr/lib32/clang/13.0.0/include/movdirintrin.h
/usr/lib32/clang/13.0.0/include/msa.h
/usr/lib32/clang/13.0.0/include/mwaitxintrin.h
/usr/lib32/clang/13.0.0/include/nmmintrin.h
/usr/lib32/clang/13.0.0/include/opencl-c-base.h
/usr/lib32/clang/13.0.0/include/opencl-c.h
/usr/lib32/clang/13.0.0/include/openmp_wrappers/__clang_openmp_device_functions.h
/usr/lib32/clang/13.0.0/include/openmp_wrappers/complex.h
/usr/lib32/clang/13.0.0/include/openmp_wrappers/complex_cmath.h
/usr/lib32/clang/13.0.0/include/openmp_wrappers/math.h
/usr/lib32/clang/13.0.0/include/pconfigintrin.h
/usr/lib32/clang/13.0.0/include/pkuintrin.h
/usr/lib32/clang/13.0.0/include/pmmintrin.h
/usr/lib32/clang/13.0.0/include/popcntintrin.h
/usr/lib32/clang/13.0.0/include/ppc_wrappers/emmintrin.h
/usr/lib32/clang/13.0.0/include/ppc_wrappers/mm_malloc.h
/usr/lib32/clang/13.0.0/include/ppc_wrappers/mmintrin.h
/usr/lib32/clang/13.0.0/include/ppc_wrappers/pmmintrin.h
/usr/lib32/clang/13.0.0/include/ppc_wrappers/smmintrin.h
/usr/lib32/clang/13.0.0/include/ppc_wrappers/tmmintrin.h
/usr/lib32/clang/13.0.0/include/ppc_wrappers/xmmintrin.h
/usr/lib32/clang/13.0.0/include/prfchwintrin.h
/usr/lib32/clang/13.0.0/include/ptwriteintrin.h
/usr/lib32/clang/13.0.0/include/rdseedintrin.h
/usr/lib32/clang/13.0.0/include/riscv_vector.h
/usr/lib32/clang/13.0.0/include/rtmintrin.h
/usr/lib32/clang/13.0.0/include/s390intrin.h
/usr/lib32/clang/13.0.0/include/serializeintrin.h
/usr/lib32/clang/13.0.0/include/sgxintrin.h
/usr/lib32/clang/13.0.0/include/shaintrin.h
/usr/lib32/clang/13.0.0/include/smmintrin.h
/usr/lib32/clang/13.0.0/include/stdalign.h
/usr/lib32/clang/13.0.0/include/stdarg.h
/usr/lib32/clang/13.0.0/include/stdatomic.h
/usr/lib32/clang/13.0.0/include/stdbool.h
/usr/lib32/clang/13.0.0/include/stddef.h
/usr/lib32/clang/13.0.0/include/stdint.h
/usr/lib32/clang/13.0.0/include/stdnoreturn.h
/usr/lib32/clang/13.0.0/include/tbmintrin.h
/usr/lib32/clang/13.0.0/include/tgmath.h
/usr/lib32/clang/13.0.0/include/tmmintrin.h
/usr/lib32/clang/13.0.0/include/tsxldtrkintrin.h
/usr/lib32/clang/13.0.0/include/uintrintrin.h
/usr/lib32/clang/13.0.0/include/unwind.h
/usr/lib32/clang/13.0.0/include/vadefs.h
/usr/lib32/clang/13.0.0/include/vaesintrin.h
/usr/lib32/clang/13.0.0/include/varargs.h
/usr/lib32/clang/13.0.0/include/vecintrin.h
/usr/lib32/clang/13.0.0/include/vpclmulqdqintrin.h
/usr/lib32/clang/13.0.0/include/waitpkgintrin.h
/usr/lib32/clang/13.0.0/include/wasm_simd128.h
/usr/lib32/clang/13.0.0/include/wbnoinvdintrin.h
/usr/lib32/clang/13.0.0/include/wmmintrin.h
/usr/lib32/clang/13.0.0/include/x86gprintrin.h
/usr/lib32/clang/13.0.0/include/x86intrin.h
/usr/lib32/clang/13.0.0/include/xmmintrin.h
/usr/lib32/clang/13.0.0/include/xopintrin.h
/usr/lib32/clang/13.0.0/include/xsavecintrin.h
/usr/lib32/clang/13.0.0/include/xsaveintrin.h
/usr/lib32/clang/13.0.0/include/xsaveoptintrin.h
/usr/lib32/clang/13.0.0/include/xsavesintrin.h
/usr/lib32/clang/13.0.0/include/xtestintrin.h
/usr/lib64/LLVMgold-13.so
/usr/lib64/clang/13.0.0/include/__clang_cuda_builtin_vars.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_cmath.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_complex_builtins.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_device_functions.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_intrinsics.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_libdevice_declares.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_math.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_math_forward_declares.h
/usr/lib64/clang/13.0.0/include/__clang_cuda_runtime_wrapper.h
/usr/lib64/clang/13.0.0/include/__clang_hip_cmath.h
/usr/lib64/clang/13.0.0/include/__clang_hip_libdevice_declares.h
/usr/lib64/clang/13.0.0/include/__clang_hip_math.h
/usr/lib64/clang/13.0.0/include/__clang_hip_runtime_wrapper.h
/usr/lib64/clang/13.0.0/include/__stddef_max_align_t.h
/usr/lib64/clang/13.0.0/include/__wmmintrin_aes.h
/usr/lib64/clang/13.0.0/include/__wmmintrin_pclmul.h
/usr/lib64/clang/13.0.0/include/adxintrin.h
/usr/lib64/clang/13.0.0/include/altivec.h
/usr/lib64/clang/13.0.0/include/ammintrin.h
/usr/lib64/clang/13.0.0/include/amxintrin.h
/usr/lib64/clang/13.0.0/include/arm64intr.h
/usr/lib64/clang/13.0.0/include/arm_acle.h
/usr/lib64/clang/13.0.0/include/arm_bf16.h
/usr/lib64/clang/13.0.0/include/arm_cde.h
/usr/lib64/clang/13.0.0/include/arm_cmse.h
/usr/lib64/clang/13.0.0/include/arm_fp16.h
/usr/lib64/clang/13.0.0/include/arm_mve.h
/usr/lib64/clang/13.0.0/include/arm_neon.h
/usr/lib64/clang/13.0.0/include/arm_sve.h
/usr/lib64/clang/13.0.0/include/armintr.h
/usr/lib64/clang/13.0.0/include/avx2intrin.h
/usr/lib64/clang/13.0.0/include/avx512bf16intrin.h
/usr/lib64/clang/13.0.0/include/avx512bitalgintrin.h
/usr/lib64/clang/13.0.0/include/avx512bwintrin.h
/usr/lib64/clang/13.0.0/include/avx512cdintrin.h
/usr/lib64/clang/13.0.0/include/avx512dqintrin.h
/usr/lib64/clang/13.0.0/include/avx512erintrin.h
/usr/lib64/clang/13.0.0/include/avx512fintrin.h
/usr/lib64/clang/13.0.0/include/avx512ifmaintrin.h
/usr/lib64/clang/13.0.0/include/avx512ifmavlintrin.h
/usr/lib64/clang/13.0.0/include/avx512pfintrin.h
/usr/lib64/clang/13.0.0/include/avx512vbmi2intrin.h
/usr/lib64/clang/13.0.0/include/avx512vbmiintrin.h
/usr/lib64/clang/13.0.0/include/avx512vbmivlintrin.h
/usr/lib64/clang/13.0.0/include/avx512vlbf16intrin.h
/usr/lib64/clang/13.0.0/include/avx512vlbitalgintrin.h
/usr/lib64/clang/13.0.0/include/avx512vlbwintrin.h
/usr/lib64/clang/13.0.0/include/avx512vlcdintrin.h
/usr/lib64/clang/13.0.0/include/avx512vldqintrin.h
/usr/lib64/clang/13.0.0/include/avx512vlintrin.h
/usr/lib64/clang/13.0.0/include/avx512vlvbmi2intrin.h
/usr/lib64/clang/13.0.0/include/avx512vlvnniintrin.h
/usr/lib64/clang/13.0.0/include/avx512vlvp2intersectintrin.h
/usr/lib64/clang/13.0.0/include/avx512vnniintrin.h
/usr/lib64/clang/13.0.0/include/avx512vp2intersectintrin.h
/usr/lib64/clang/13.0.0/include/avx512vpopcntdqintrin.h
/usr/lib64/clang/13.0.0/include/avx512vpopcntdqvlintrin.h
/usr/lib64/clang/13.0.0/include/avxintrin.h
/usr/lib64/clang/13.0.0/include/avxvnniintrin.h
/usr/lib64/clang/13.0.0/include/bmi2intrin.h
/usr/lib64/clang/13.0.0/include/bmiintrin.h
/usr/lib64/clang/13.0.0/include/builtins.h
/usr/lib64/clang/13.0.0/include/cet.h
/usr/lib64/clang/13.0.0/include/cetintrin.h
/usr/lib64/clang/13.0.0/include/cldemoteintrin.h
/usr/lib64/clang/13.0.0/include/clflushoptintrin.h
/usr/lib64/clang/13.0.0/include/clwbintrin.h
/usr/lib64/clang/13.0.0/include/clzerointrin.h
/usr/lib64/clang/13.0.0/include/cpuid.h
/usr/lib64/clang/13.0.0/include/emmintrin.h
/usr/lib64/clang/13.0.0/include/enqcmdintrin.h
/usr/lib64/clang/13.0.0/include/f16cintrin.h
/usr/lib64/clang/13.0.0/include/float.h
/usr/lib64/clang/13.0.0/include/fma4intrin.h
/usr/lib64/clang/13.0.0/include/fmaintrin.h
/usr/lib64/clang/13.0.0/include/fuzzer/FuzzedDataProvider.h
/usr/lib64/clang/13.0.0/include/fxsrintrin.h
/usr/lib64/clang/13.0.0/include/gfniintrin.h
/usr/lib64/clang/13.0.0/include/hexagon_circ_brev_intrinsics.h
/usr/lib64/clang/13.0.0/include/hexagon_protos.h
/usr/lib64/clang/13.0.0/include/hexagon_types.h
/usr/lib64/clang/13.0.0/include/hresetintrin.h
/usr/lib64/clang/13.0.0/include/htmintrin.h
/usr/lib64/clang/13.0.0/include/htmxlintrin.h
/usr/lib64/clang/13.0.0/include/hvx_hexagon_protos.h
/usr/lib64/clang/13.0.0/include/ia32intrin.h
/usr/lib64/clang/13.0.0/include/immintrin.h
/usr/lib64/clang/13.0.0/include/intrin.h
/usr/lib64/clang/13.0.0/include/inttypes.h
/usr/lib64/clang/13.0.0/include/invpcidintrin.h
/usr/lib64/clang/13.0.0/include/iso646.h
/usr/lib64/clang/13.0.0/include/keylockerintrin.h
/usr/lib64/clang/13.0.0/include/limits.h
/usr/lib64/clang/13.0.0/include/lwpintrin.h
/usr/lib64/clang/13.0.0/include/lzcntintrin.h
/usr/lib64/clang/13.0.0/include/mm3dnow.h
/usr/lib64/clang/13.0.0/include/mm_malloc.h
/usr/lib64/clang/13.0.0/include/mmintrin.h
/usr/lib64/clang/13.0.0/include/movdirintrin.h
/usr/lib64/clang/13.0.0/include/msa.h
/usr/lib64/clang/13.0.0/include/mwaitxintrin.h
/usr/lib64/clang/13.0.0/include/nmmintrin.h
/usr/lib64/clang/13.0.0/include/omp-tools.h
/usr/lib64/clang/13.0.0/include/omp.h
/usr/lib64/clang/13.0.0/include/ompt.h
/usr/lib64/clang/13.0.0/include/opencl-c-base.h
/usr/lib64/clang/13.0.0/include/opencl-c.h
/usr/lib64/clang/13.0.0/include/openmp_wrappers/__clang_openmp_device_functions.h
/usr/lib64/clang/13.0.0/include/openmp_wrappers/complex.h
/usr/lib64/clang/13.0.0/include/openmp_wrappers/complex_cmath.h
/usr/lib64/clang/13.0.0/include/openmp_wrappers/math.h
/usr/lib64/clang/13.0.0/include/pconfigintrin.h
/usr/lib64/clang/13.0.0/include/pkuintrin.h
/usr/lib64/clang/13.0.0/include/pmmintrin.h
/usr/lib64/clang/13.0.0/include/popcntintrin.h
/usr/lib64/clang/13.0.0/include/ppc_wrappers/emmintrin.h
/usr/lib64/clang/13.0.0/include/ppc_wrappers/mm_malloc.h
/usr/lib64/clang/13.0.0/include/ppc_wrappers/mmintrin.h
/usr/lib64/clang/13.0.0/include/ppc_wrappers/pmmintrin.h
/usr/lib64/clang/13.0.0/include/ppc_wrappers/smmintrin.h
/usr/lib64/clang/13.0.0/include/ppc_wrappers/tmmintrin.h
/usr/lib64/clang/13.0.0/include/ppc_wrappers/xmmintrin.h
/usr/lib64/clang/13.0.0/include/prfchwintrin.h
/usr/lib64/clang/13.0.0/include/ptwriteintrin.h
/usr/lib64/clang/13.0.0/include/rdseedintrin.h
/usr/lib64/clang/13.0.0/include/riscv_vector.h
/usr/lib64/clang/13.0.0/include/rtmintrin.h
/usr/lib64/clang/13.0.0/include/s390intrin.h
/usr/lib64/clang/13.0.0/include/sanitizer/allocator_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/asan_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/common_interface_defs.h
/usr/lib64/clang/13.0.0/include/sanitizer/coverage_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/dfsan_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/hwasan_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/linux_syscall_hooks.h
/usr/lib64/clang/13.0.0/include/sanitizer/lsan_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/msan_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/netbsd_syscall_hooks.h
/usr/lib64/clang/13.0.0/include/sanitizer/scudo_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/tsan_interface.h
/usr/lib64/clang/13.0.0/include/sanitizer/tsan_interface_atomic.h
/usr/lib64/clang/13.0.0/include/sanitizer/ubsan_interface.h
/usr/lib64/clang/13.0.0/include/serializeintrin.h
/usr/lib64/clang/13.0.0/include/sgxintrin.h
/usr/lib64/clang/13.0.0/include/shaintrin.h
/usr/lib64/clang/13.0.0/include/smmintrin.h
/usr/lib64/clang/13.0.0/include/stdalign.h
/usr/lib64/clang/13.0.0/include/stdarg.h
/usr/lib64/clang/13.0.0/include/stdatomic.h
/usr/lib64/clang/13.0.0/include/stdbool.h
/usr/lib64/clang/13.0.0/include/stddef.h
/usr/lib64/clang/13.0.0/include/stdint.h
/usr/lib64/clang/13.0.0/include/stdnoreturn.h
/usr/lib64/clang/13.0.0/include/tbmintrin.h
/usr/lib64/clang/13.0.0/include/tgmath.h
/usr/lib64/clang/13.0.0/include/tmmintrin.h
/usr/lib64/clang/13.0.0/include/tsxldtrkintrin.h
/usr/lib64/clang/13.0.0/include/uintrintrin.h
/usr/lib64/clang/13.0.0/include/unwind.h
/usr/lib64/clang/13.0.0/include/vadefs.h
/usr/lib64/clang/13.0.0/include/vaesintrin.h
/usr/lib64/clang/13.0.0/include/varargs.h
/usr/lib64/clang/13.0.0/include/vecintrin.h
/usr/lib64/clang/13.0.0/include/vpclmulqdqintrin.h
/usr/lib64/clang/13.0.0/include/waitpkgintrin.h
/usr/lib64/clang/13.0.0/include/wasm_simd128.h
/usr/lib64/clang/13.0.0/include/wbnoinvdintrin.h
/usr/lib64/clang/13.0.0/include/wmmintrin.h
/usr/lib64/clang/13.0.0/include/x86gprintrin.h
/usr/lib64/clang/13.0.0/include/x86intrin.h
/usr/lib64/clang/13.0.0/include/xmmintrin.h
/usr/lib64/clang/13.0.0/include/xopintrin.h
/usr/lib64/clang/13.0.0/include/xray/xray_interface.h
/usr/lib64/clang/13.0.0/include/xray/xray_log_interface.h
/usr/lib64/clang/13.0.0/include/xray/xray_records.h
/usr/lib64/clang/13.0.0/include/xsavecintrin.h
/usr/lib64/clang/13.0.0/include/xsaveintrin.h
/usr/lib64/clang/13.0.0/include/xsaveoptintrin.h
/usr/lib64/clang/13.0.0/include/xsavesintrin.h
/usr/lib64/clang/13.0.0/include/xtestintrin.h

%files dev32
%defattr(-,root,root,-)
/usr/lib32/LLVMgold.so
/usr/lib32/cmake/clang/AddClang.cmake
/usr/lib32/cmake/clang/ClangConfig.cmake
/usr/lib32/cmake/clang/ClangTargets-relwithdebinfo.cmake
/usr/lib32/cmake/clang/ClangTargets.cmake
/usr/lib32/cmake/llvm/AddLLVM.cmake
/usr/lib32/cmake/llvm/AddLLVMDefinitions.cmake
/usr/lib32/cmake/llvm/AddOCaml.cmake
/usr/lib32/cmake/llvm/AddSphinxTarget.cmake
/usr/lib32/cmake/llvm/CheckAtomic.cmake
/usr/lib32/cmake/llvm/CheckCompilerVersion.cmake
/usr/lib32/cmake/llvm/ChooseMSVCCRT.cmake
/usr/lib32/cmake/llvm/CrossCompile.cmake
/usr/lib32/cmake/llvm/DetermineGCCCompatible.cmake
/usr/lib32/cmake/llvm/FindGRPC.cmake
/usr/lib32/cmake/llvm/FindLibpfm.cmake
/usr/lib32/cmake/llvm/FindOCaml.cmake
/usr/lib32/cmake/llvm/FindSphinx.cmake
/usr/lib32/cmake/llvm/FindZ3.cmake
/usr/lib32/cmake/llvm/GenerateVersionFromVCS.cmake
/usr/lib32/cmake/llvm/GetErrcMessages.cmake
/usr/lib32/cmake/llvm/GetLibraryName.cmake
/usr/lib32/cmake/llvm/HandleLLVMOptions.cmake
/usr/lib32/cmake/llvm/HandleLLVMStdlib.cmake
/usr/lib32/cmake/llvm/LLVM-Build.cmake
/usr/lib32/cmake/llvm/LLVM-Config.cmake
/usr/lib32/cmake/llvm/LLVMCheckLinkerFlag.cmake
/usr/lib32/cmake/llvm/LLVMConfig.cmake
/usr/lib32/cmake/llvm/LLVMConfigExtensions.cmake
/usr/lib32/cmake/llvm/LLVMConfigVersion.cmake
/usr/lib32/cmake/llvm/LLVMDistributionSupport.cmake
/usr/lib32/cmake/llvm/LLVMExports-relwithdebinfo.cmake
/usr/lib32/cmake/llvm/LLVMExports.cmake
/usr/lib32/cmake/llvm/LLVMExternalProjectUtils.cmake
/usr/lib32/cmake/llvm/LLVMInstallSymlink.cmake
/usr/lib32/cmake/llvm/LLVMProcessSources.cmake
/usr/lib32/cmake/llvm/TableGen.cmake
/usr/lib32/cmake/llvm/TensorFlowCompile.cmake
/usr/lib32/cmake/llvm/UseLibtool.cmake
/usr/lib32/cmake/llvm/VersionFromVCS.cmake
/usr/lib32/libLLVM.so
/usr/lib32/libLTO.so
/usr/lib32/libRemarks.so
/usr/lib32/libclang-cpp.so
/usr/lib32/libclang.so
/usr/lib32/pkgconfig/32LLVMSPIRVLib.pc
/usr/lib32/pkgconfig/32SPIRV-Headers.pc
/usr/lib32/pkgconfig/LLVMSPIRVLib.pc
/usr/lib32/pkgconfig/SPIRV-Headers.pc

%files extras-libclang
%defattr(-,root,root,-)
/usr/lib64/libclang.so.13.0.0

%files extras-libclang-cpp
%defattr(-,root,root,-)
/usr/lib64/libclang-cpp.so.13

%files extras-libllvm
%defattr(-,root,root,-)
/usr/lib64/libLLVM.so.13

%files lib
%defattr(-,root,root,-)
/usr/lib/bfd-plugins/LLVMgold-13.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan-i386.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.asan-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.dyndd-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.hwasan_aliases-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.memprof-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo-i386.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_minimal-i386.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_minimal-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_standalone-i386.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.scudo_standalone-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_minimal-i386.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_minimal-x86_64.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone-i386.so
/usr/lib64/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone-x86_64.so
/usr/lib64/libLTO.so.13
/usr/lib64/libRemarks.so.13
/usr/lib64/libclang.so.13
/usr/lib64/liblldb.so.13
/usr/lib64/liblldb.so.13.0.0
/usr/lib64/liblldbIntelFeatures.so.13

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libLLVM.so.13
/usr/lib32/libLTO.so.13
/usr/lib32/libRemarks.so.13
/usr/lib32/libclang-cpp.so.13
/usr/lib32/libclang.so.13
/usr/lib32/libclang.so.13.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/llvm13/11156021d878bfcbdf2563b4f65db32b4d9f92a3
/usr/share/package-licenses/llvm13/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/llvm13/45c2429b5881295597e96c81fc50f7b8a42e769f
/usr/share/package-licenses/llvm13/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/llvm13/5a99e7077ee89ba92fb3f584855e8970096cd5dc
/usr/share/package-licenses/llvm13/6b655b0685aa7ee33fa1e02103b3bf22ed06e099
/usr/share/package-licenses/llvm13/72c865be698cefc46549ed61e279f98432364fca
/usr/share/package-licenses/llvm13/7b75a5471af8b3d49e60df0a5d72f95ea8214231
/usr/share/package-licenses/llvm13/85c0f2884378413881b4d3e27fc24b220f71889b
/usr/share/package-licenses/llvm13/8737af83de0d40386dca9a4abe2b6faa83cb4750
/usr/share/package-licenses/llvm13/8af372ad1edbed2cfaf0e79d25f7136ec6e55b47
/usr/share/package-licenses/llvm13/8d3b142938f83e7045951089b52676a5605eee37
/usr/share/package-licenses/llvm13/8f178caf2a2d6e6c711a30da69077572df356cf6
/usr/share/package-licenses/llvm13/9a84200f47e09abfbde1a6b25028460451b23d03
/usr/share/package-licenses/llvm13/a1691103171dc1d21cfa85f1d4809a16b9f1367f
/usr/share/package-licenses/llvm13/af07f365643f841c69797e9059b66f0bd847f1cd
/usr/share/package-licenses/llvm13/b5d4ab4d1191e592c03310adfbe90d99a46bf9d7
/usr/share/package-licenses/llvm13/c01c212bdf3925189f673e2081b44094023860ea
/usr/share/package-licenses/llvm13/ce27417c74ca5ad6d0b5c96ede8ff82e4d87900f
/usr/share/package-licenses/llvm13/d79062af10a33188d4a74d976323845a2cf9023d
/usr/share/package-licenses/llvm13/db1f866b29c6a191752c7c5924b7572cdbc47c34
/usr/share/package-licenses/llvm13/e3cccabb67bd491a643d32a7d2b65b49836e626d
/usr/share/package-licenses/llvm13/f226af67862c0c7a0e921e24672a3a1375691e3e
/usr/share/package-licenses/llvm13/f4359b9da55a3b9e4d9513eb79cacf125fb49e7b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libLLVMAArch64AsmParser.a
/usr/lib32/libLLVMAArch64CodeGen.a
/usr/lib32/libLLVMAArch64Desc.a
/usr/lib32/libLLVMAArch64Disassembler.a
/usr/lib32/libLLVMAArch64Info.a
/usr/lib32/libLLVMAArch64Utils.a
/usr/lib32/libLLVMAMDGPUAsmParser.a
/usr/lib32/libLLVMAMDGPUCodeGen.a
/usr/lib32/libLLVMAMDGPUDesc.a
/usr/lib32/libLLVMAMDGPUDisassembler.a
/usr/lib32/libLLVMAMDGPUInfo.a
/usr/lib32/libLLVMAMDGPUUtils.a
/usr/lib32/libLLVMARMAsmParser.a
/usr/lib32/libLLVMARMCodeGen.a
/usr/lib32/libLLVMARMDesc.a
/usr/lib32/libLLVMARMDisassembler.a
/usr/lib32/libLLVMARMInfo.a
/usr/lib32/libLLVMARMUtils.a
/usr/lib32/libLLVMAVRAsmParser.a
/usr/lib32/libLLVMAVRCodeGen.a
/usr/lib32/libLLVMAVRDesc.a
/usr/lib32/libLLVMAVRDisassembler.a
/usr/lib32/libLLVMAVRInfo.a
/usr/lib32/libLLVMAggressiveInstCombine.a
/usr/lib32/libLLVMAnalysis.a
/usr/lib32/libLLVMAsmParser.a
/usr/lib32/libLLVMAsmPrinter.a
/usr/lib32/libLLVMBPFAsmParser.a
/usr/lib32/libLLVMBPFCodeGen.a
/usr/lib32/libLLVMBPFDesc.a
/usr/lib32/libLLVMBPFDisassembler.a
/usr/lib32/libLLVMBPFInfo.a
/usr/lib32/libLLVMBinaryFormat.a
/usr/lib32/libLLVMBitReader.a
/usr/lib32/libLLVMBitWriter.a
/usr/lib32/libLLVMBitstreamReader.a
/usr/lib32/libLLVMCFGuard.a
/usr/lib32/libLLVMCFIVerify.a
/usr/lib32/libLLVMCodeGen.a
/usr/lib32/libLLVMCore.a
/usr/lib32/libLLVMCoroutines.a
/usr/lib32/libLLVMCoverage.a
/usr/lib32/libLLVMDWARFLinker.a
/usr/lib32/libLLVMDWP.a
/usr/lib32/libLLVMDebugInfoCodeView.a
/usr/lib32/libLLVMDebugInfoDWARF.a
/usr/lib32/libLLVMDebugInfoGSYM.a
/usr/lib32/libLLVMDebugInfoMSF.a
/usr/lib32/libLLVMDebugInfoPDB.a
/usr/lib32/libLLVMDemangle.a
/usr/lib32/libLLVMDlltoolDriver.a
/usr/lib32/libLLVMExecutionEngine.a
/usr/lib32/libLLVMExegesis.a
/usr/lib32/libLLVMExegesisAArch64.a
/usr/lib32/libLLVMExegesisMips.a
/usr/lib32/libLLVMExegesisPowerPC.a
/usr/lib32/libLLVMExegesisX86.a
/usr/lib32/libLLVMExtensions.a
/usr/lib32/libLLVMFileCheck.a
/usr/lib32/libLLVMFrontendOpenACC.a
/usr/lib32/libLLVMFrontendOpenMP.a
/usr/lib32/libLLVMFuzzMutate.a
/usr/lib32/libLLVMGlobalISel.a
/usr/lib32/libLLVMHexagonAsmParser.a
/usr/lib32/libLLVMHexagonCodeGen.a
/usr/lib32/libLLVMHexagonDesc.a
/usr/lib32/libLLVMHexagonDisassembler.a
/usr/lib32/libLLVMHexagonInfo.a
/usr/lib32/libLLVMIRReader.a
/usr/lib32/libLLVMInstCombine.a
/usr/lib32/libLLVMInstrumentation.a
/usr/lib32/libLLVMInterfaceStub.a
/usr/lib32/libLLVMInterpreter.a
/usr/lib32/libLLVMJITLink.a
/usr/lib32/libLLVMLTO.a
/usr/lib32/libLLVMLanaiAsmParser.a
/usr/lib32/libLLVMLanaiCodeGen.a
/usr/lib32/libLLVMLanaiDesc.a
/usr/lib32/libLLVMLanaiDisassembler.a
/usr/lib32/libLLVMLanaiInfo.a
/usr/lib32/libLLVMLibDriver.a
/usr/lib32/libLLVMLineEditor.a
/usr/lib32/libLLVMLinker.a
/usr/lib32/libLLVMMC.a
/usr/lib32/libLLVMMCA.a
/usr/lib32/libLLVMMCACustomBehaviourAMDGPU.a
/usr/lib32/libLLVMMCDisassembler.a
/usr/lib32/libLLVMMCJIT.a
/usr/lib32/libLLVMMCParser.a
/usr/lib32/libLLVMMIRParser.a
/usr/lib32/libLLVMMSP430AsmParser.a
/usr/lib32/libLLVMMSP430CodeGen.a
/usr/lib32/libLLVMMSP430Desc.a
/usr/lib32/libLLVMMSP430Disassembler.a
/usr/lib32/libLLVMMSP430Info.a
/usr/lib32/libLLVMMipsAsmParser.a
/usr/lib32/libLLVMMipsCodeGen.a
/usr/lib32/libLLVMMipsDesc.a
/usr/lib32/libLLVMMipsDisassembler.a
/usr/lib32/libLLVMMipsInfo.a
/usr/lib32/libLLVMNVPTXCodeGen.a
/usr/lib32/libLLVMNVPTXDesc.a
/usr/lib32/libLLVMNVPTXInfo.a
/usr/lib32/libLLVMObjCARCOpts.a
/usr/lib32/libLLVMObject.a
/usr/lib32/libLLVMObjectYAML.a
/usr/lib32/libLLVMOption.a
/usr/lib32/libLLVMOrcJIT.a
/usr/lib32/libLLVMOrcShared.a
/usr/lib32/libLLVMOrcTargetProcess.a
/usr/lib32/libLLVMPasses.a
/usr/lib32/libLLVMPowerPCAsmParser.a
/usr/lib32/libLLVMPowerPCCodeGen.a
/usr/lib32/libLLVMPowerPCDesc.a
/usr/lib32/libLLVMPowerPCDisassembler.a
/usr/lib32/libLLVMPowerPCInfo.a
/usr/lib32/libLLVMProfileData.a
/usr/lib32/libLLVMRISCVAsmParser.a
/usr/lib32/libLLVMRISCVCodeGen.a
/usr/lib32/libLLVMRISCVDesc.a
/usr/lib32/libLLVMRISCVDisassembler.a
/usr/lib32/libLLVMRISCVInfo.a
/usr/lib32/libLLVMRemarks.a
/usr/lib32/libLLVMRuntimeDyld.a
/usr/lib32/libLLVMSPIRVLib.a
/usr/lib32/libLLVMScalarOpts.a
/usr/lib32/libLLVMSelectionDAG.a
/usr/lib32/libLLVMSparcAsmParser.a
/usr/lib32/libLLVMSparcCodeGen.a
/usr/lib32/libLLVMSparcDesc.a
/usr/lib32/libLLVMSparcDisassembler.a
/usr/lib32/libLLVMSparcInfo.a
/usr/lib32/libLLVMSupport.a
/usr/lib32/libLLVMSymbolize.a
/usr/lib32/libLLVMSystemZAsmParser.a
/usr/lib32/libLLVMSystemZCodeGen.a
/usr/lib32/libLLVMSystemZDesc.a
/usr/lib32/libLLVMSystemZDisassembler.a
/usr/lib32/libLLVMSystemZInfo.a
/usr/lib32/libLLVMTableGen.a
/usr/lib32/libLLVMTableGenGlobalISel.a
/usr/lib32/libLLVMTarget.a
/usr/lib32/libLLVMTextAPI.a
/usr/lib32/libLLVMTransformUtils.a
/usr/lib32/libLLVMVectorize.a
/usr/lib32/libLLVMWebAssemblyAsmParser.a
/usr/lib32/libLLVMWebAssemblyCodeGen.a
/usr/lib32/libLLVMWebAssemblyDesc.a
/usr/lib32/libLLVMWebAssemblyDisassembler.a
/usr/lib32/libLLVMWebAssemblyInfo.a
/usr/lib32/libLLVMWebAssemblyUtils.a
/usr/lib32/libLLVMWindowsManifest.a
/usr/lib32/libLLVMX86AsmParser.a
/usr/lib32/libLLVMX86CodeGen.a
/usr/lib32/libLLVMX86Desc.a
/usr/lib32/libLLVMX86Disassembler.a
/usr/lib32/libLLVMX86Info.a
/usr/lib32/libLLVMXCoreCodeGen.a
/usr/lib32/libLLVMXCoreDesc.a
/usr/lib32/libLLVMXCoreDisassembler.a
/usr/lib32/libLLVMXCoreInfo.a
/usr/lib32/libLLVMXRay.a
/usr/lib32/libLLVMipo.a
/usr/lib32/libclangAPINotes.a
/usr/lib32/libclangARCMigrate.a
/usr/lib32/libclangAST.a
/usr/lib32/libclangASTMatchers.a
/usr/lib32/libclangAnalysis.a
/usr/lib32/libclangBasic.a
/usr/lib32/libclangCodeGen.a
/usr/lib32/libclangCrossTU.a
/usr/lib32/libclangDependencyScanning.a
/usr/lib32/libclangDirectoryWatcher.a
/usr/lib32/libclangDriver.a
/usr/lib32/libclangDynamicASTMatchers.a
/usr/lib32/libclangEdit.a
/usr/lib32/libclangFormat.a
/usr/lib32/libclangFrontend.a
/usr/lib32/libclangFrontendTool.a
/usr/lib32/libclangHandleCXX.a
/usr/lib32/libclangHandleLLVM.a
/usr/lib32/libclangIndex.a
/usr/lib32/libclangIndexSerialization.a
/usr/lib32/libclangInterpreter.a
/usr/lib32/libclangLex.a
/usr/lib32/libclangParse.a
/usr/lib32/libclangRewrite.a
/usr/lib32/libclangRewriteFrontend.a
/usr/lib32/libclangSema.a
/usr/lib32/libclangSerialization.a
/usr/lib32/libclangStaticAnalyzerCheckers.a
/usr/lib32/libclangStaticAnalyzerCore.a
/usr/lib32/libclangStaticAnalyzerFrontend.a
/usr/lib32/libclangTesting.a
/usr/lib32/libclangTooling.a
/usr/lib32/libclangToolingASTDiff.a
/usr/lib32/libclangToolingCore.a
/usr/lib32/libclangToolingInclusions.a
/usr/lib32/libclangToolingRefactoring.a
/usr/lib32/libclangToolingSyntax.a
/usr/lib32/libclangTransformer.a
